#!/usr/bin/env bash

# Color styling.
TEXT_BOLD=$(tput bold)

COLOR_BLACK=$(tput setaf 0)
COLOR_RED=$(tput setaf 1)
COLOR_GREEN=$(tput setaf 2)
COLOR_YELLOW=$(tput setaf 3)
COLOR_BLUE=$(tput setaf 4)
COLOR_MAGENTA=$(tput setaf 5)
COLOR_CYAN=$(tput setaf 6)
COLOR_WHITE=$(tput setaf 7)

ALLTEXT_NORMAL=$(tput sgr0)


# Sanity check the request.
APP_NAME=$1
if [ "$APP_NAME" == "" ]; then
    echo -e "$COLOR_RED""$TEXT_BOLD""!! Error,"\
        "$ALLTEXT_NORMAL""No App name specified to be halted."
    exit 1
fi

# Kill any zombie StickyClockSettings ConfigDialog.
# Like: 0x03400007  0 lubuntu StickyClockSettings
SETTINGS_RESULT=$(wmctrl -l | egrep "$APP_NAME""Settings""$")
SETTINGS_PROC=${SETTINGS_RESULT:0:10}
SETTINGS_NAME=${SETTINGS_RESULT:22}
if [ "$SETTINGS_PROC" != "" ]; then
    echo -e "$COLOR_YELLOW""$TEXT_BOLD""-- Warning,"\
        "$ALLTEXT_NORMAL""Active ConfigDialog is being shutdown."
    xkill -id ""$SETTINGS_PROC"" 1>/dev/null 2>/dev/null
else
    echo "-- No Active ConfigDialog to shutdown."
fi

# Kill any zombie StickyClock.
# Like: 0x03400007  0 lubuntu StickyClock
SETTINGS_RESULT=$(wmctrl -l | egrep "$APP_NAME""$")
SETTINGS_PROC=${SETTINGS_RESULT:0:10}
SETTINGS_NAME=${SETTINGS_RESULT:22}
if [ "$SETTINGS_PROC" != "" ]; then
    echo -e "$COLOR_YELLOW""$TEXT_BOLD""-- Warning,"\
        "$ALLTEXT_NORMAL""Active StickyClock is being shutdown."
    xkill -id ""$SETTINGS_PROC"" 1>/dev/null 2>/dev/null
else
    echo "-- No Active StickyClock to shutdown."
fi
